title: Diana Spahieva
logo: /assets/img/headshot.jpeg
description: Technical Skills: Python, R, SQL, AWS, Keras, ETL, Docker, Pandas, Linux, CICD, Django, Selenium
#show_downloads: true
theme: jekyll-theme-minimal #cayman
